version: '3.9'
services:
  postgres:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10

  postgres_webmanagement:
    image: dpage/pgadmin4:7.8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgres

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

      DB_USERNAME_PRODUCTION: test
      DB_PASSWORD_PRODUCTION: test
      DB_ROLE_PRODUCTION: readWrite
      DB_NAME_PRODUCTION: production

    volumes:
      - ./docker/scripts/mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - 27017:27017

  mongodb_express:
    image: mongo-express:1.0.0-20
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongodb:27017/

  